                                                                                                                                                                        #define HOHOHOHOHO class
                                                                                                                                                                        #define hOHOHOHOHO MyCircularBuffer
                                                                                                                                                                        #define HoHOHOHOHO :
                                                                                                                                                                        #define hoHOHOHOHO public
                                                                                                                                                                        #define HOhOHOHOHO circularBuffer
                                                                                                                                                                        #define hOhOHOHOHO {
                                                                                                                                                                        #define HohOHOHOHO public:
                                                                                                                                                                        #define hohOHOHOHO (
                                                                                                                                                                        #define HOHoHOHOHO int
                                                                                                                                                                        #define hOHoHOHOHO size
                                                                                                                                                                        #define HoHoHOHOHO )
                                                                                                                                                                        #define hoHoHOHOHO }
                                                                                                                                                                        #define HOhoHOHOHO countOccurences
                                                                                                                                                                        #define hOhoHOHOHO mod
                                                                                                                                                                        #define HohoHOHOHO ;
                                                                                                                                                                        #define hohoHOHOHO countAll
                                                                                                                                                                        #define HOHOhOHOHO canA1
                                                                                                                                                                        #define hOHOhOHOHO canA2
                                                                                                                                                                        #define HoHOhOHOHO canB1
                                                                                                                                                                        #define hoHOhOHOHO canB2
                                                                                                                                                                        #define HOhOhOHOHO MyCircularBuffer::countOccurences
                                                                                                                                                                        #define hOhOhOHOHO count
                                                                                                                                                                        #define HohOhOHOHO =
                                                                                                                                                                        #define hohOhOHOHO 0
                                                                                                                                                                        #define HOHohOHOHO for
                                                                                                                                                                        #define hOHohOHOHO i
                                                                                                                                                                        #define HoHohOHOHO head
                                                                                                                                                                        #define hoHohOHOHO !=
                                                                                                                                                                        #define HOhohOHOHO tail
                                                                                                                                                                        #define hOhohOHOHO +
                                                                                                                                                                        #define HohohOHOHO 1
                                                                                                                                                                        #define hohohOHOHO %
                                                                                                                                                                        #define HOHOHoHOHO if
                                                                                                                                                                        #define hOHOHoHOHO buf
                                                                                                                                                                        #define HoHOHoHOHO [
                                                                                                                                                                        #define hoHOHoHOHO ]
                                                                                                                                                                        #define HOhOHoHOHO 2
                                                                                                                                                                        #define hOhOHoHOHO ==
                                                                                                                                                                        #define HohOHoHOHO ++
                                                                                                                                                                        #define hohOHoHOHO return
                                                                                                                                                                        #define HOHoHoHOHO MyCircularBuffer::countAll
                                                                                                                                                                        #define hOHoHoHOHO MyCircularBuffer::canA1
                                                                                                                                                                        #define HoHoHoHOHO <
                                                                                                                                                                        #define hoHoHoHOHO 10
                                                                                                                                                                        #define HOhoHoHOHO MyCircularBuffer::canA2
                                                                                                                                                                        #define hOhoHoHOHO >
                                                                                                                                                                        #define HohoHoHOHO MyCircularBuffer::canB1
                                                                                                                                                                        #define hohoHoHOHO 3
                                                                                                                                                                        #define HOHOhoHOHO &&
                                                                                                                                                                        #define hOHOhoHOHO peak_head
                                                                                                                                                                        #define HoHOhoHOHO MyCircularBuffer::canB2
                                                                                                                                                                        #define hoHOhoHOHO 7
                                                                                                                                                                        #define HOhOhoHOHO MyMonitor
                                                                                                                                                                        #define hOhOhoHOHO Monitor
                                                                                                                                                                        #define HohOhoHOHO private:
                                                                                                                                                                        #define hohOhoHOHO enum
                                                                                                                                                                        #define HOHohoHOHO processes
                                                                                                                                                                        #define hOHohoHOHO A1
                                                                                                                                                                        #define HoHohoHOHO ,
                                                                                                                                                                        #define hoHohoHOHO A2
                                                                                                                                                                        #define HOhohoHOHO B1
                                                                                                                                                                        #define hOhohoHOHO B2
                                                                                                                                                                        #define HohohoHOHO Condition
                                                                                                                                                                        #define hohohoHOHO conditions
                                                                                                                                                                        #define HOHOHOhOHO 4
                                                                                                                                                                        #define hOHOHOhOHO waiting
                                                                                                                                                                        #define HoHOHOhOHO *buf
                                                                                                                                                                        #define hoHOHOhOHO bufsize
                                                                                                                                                                        #define HOhOHOhOHO new
                                                                                                                                                                        #define hOhOHOhOHO void
                                                                                                                                                                        #define HohOHOhOHO test
                                                                                                                                                                        #define hohOHOhOHO proc
                                                                                                                                                                        #define HOHoHOhOHO *a1
                                                                                                                                                                        #define hOHoHOhOHO *a2
                                                                                                                                                                        #define HoHoHOhOHO *b1
                                                                                                                                                                        #define hoHoHOhOHO *b2
                                                                                                                                                                        #define HOhoHOhOHO static
                                                                                                                                                                        #define hOhoHOhOHO *a1_helper
                                                                                                                                                                        #define HohoHOhOHO *context
                                                                                                                                                                        #define hohoHOhOHO MyMonitor*
                                                                                                                                                                        #define HOHOhOhOHO context
                                                                                                                                                                        #define hOHOhOhOHO ->
                                                                                                                                                                        #define HoHOhOhOHO a1
                                                                                                                                                                        #define hoHOhOhOHO *a2_helper
                                                                                                                                                                        #define HOhOhOhOHO a2
                                                                                                                                                                        #define hOhOhOhOHO *b1_helper
                                                                                                                                                                        #define HohOhOhOHO b1
                                                                                                                                                                        #define hohOhOhOHO *b2_helper
                                                                                                                                                                        #define HOHohOhOHO b2
                                                                                                                                                                        #define hOHohOhOHO MyMonitor::test
                                                                                                                                                                        #define HoHohOhOHO if(
                                                                                                                                                                        #define hoHohOhOHO !
                                                                                                                                                                        #define HOhohOhOHO processes::A1
                                                                                                                                                                        #define hOhohOhOHO signal(
                                                                                                                                                                        #define HohohOhOHO );
                                                                                                                                                                        #define hohohOhOHO else
                                                                                                                                                                        #define HOHOHohOHO processes::A2
                                                                                                                                                                        #define hOHOHohOHO processes::B1
                                                                                                                                                                        #define HoHOHohOHO processes::B2
                                                                                                                                                                        #define hoHOHohOHO leave
                                                                                                                                                                        #define HOhOHohOHO *MyMonitor::a1
                                                                                                                                                                        #define hOhOHohOHO counter
                                                                                                                                                                        #define HohOHohOHO srand
                                                                                                                                                                        #define hohOHohOHO time
                                                                                                                                                                        #define HOHoHohOHO NULL
                                                                                                                                                                        #define hOHoHohOHO 400
                                                                                                                                                                        #define HoHoHohOHO while
                                                                                                                                                                        #define hoHoHohOHO enter
                                                                                                                                                                        #define HOhoHohOHO wait
                                                                                                                                                                        #define hOhoHohOHO --
                                                                                                                                                                        #define HohoHohOHO put
                                                                                                                                                                        #define hohoHohOHO std::cout
                                                                                                                                                                        #define HOHOhohOHO <<
                                                                                                                                                                        #define hOHOhohOHO std::endl
                                                                                                                                                                        #define HoHOhohOHO 100
                                                                                                                                                                        #define hoHOhohOHO usleep
                                                                                                                                                                        #define HOhOhohOHO 200000
                                                                                                                                                                        #define hOhOhohOHO *
                                                                                                                                                                        #define HohOhohOHO rand()
                                                                                                                                                                        #define hohOhohOHO *MyMonitor::a2
                                                                                                                                                                        #define HOHohohOHO 200
                                                                                                                                                                        #define hOHohohOHO *MyMonitor::b1
                                                                                                                                                                        #define HoHohohOHO val
                                                                                                                                                                        #define hoHohohOHO get
                                                                                                                                                                        #define HOhohohOHO *MyMonitor::b2
                                                                                                                                                                        #define hOhohohOHO 800
                                                                                                                                                                        #define HohohohOHO main
                                                                                                                                                                        #define hohohohOHO *monitor
                                                                                                                                                                        #define HOHOHOHoHO 30
                                                                                                                                                                        #define hOHOHOHoHO pthread_t
                                                                                                                                                                        #define HoHOHOHoHO pthread_create(
                                                                                                                                                                        #define hoHOHOHoHO &A1
                                                                                                                                                                        #define HOhOHOHoHO MyMonitor::a1_helper
                                                                                                                                                                        #define hOhOHOHoHO monitor
                                                                                                                                                                        #define HohOHOHoHO &A2
                                                                                                                                                                        #define hohOHOHoHO MyMonitor::a2_helper
                                                                                                                                                                        #define HOHoHOHoHO &B1
                                                                                                                                                                        #define hOHoHOHoHO MyMonitor::b1_helper
                                                                                                                                                                        #define HoHoHOHoHO &B2
                                                                                                                                                                        #define hoHoHOHoHO MyMonitor::b2_helper
                                                                                                                                                                        #define HOhoHOHoHO pthread_join(
                                                                                                                                                                        #define hOhoHOHoHO Semaphore
                                                                                                                                                                        #define HohoHOHoHO value
                                                                                                                                                                        #define hohoHOHoHO sem_init
                                                                                                                                                                        #define HOHOhOHoHO &
                                                                                                                                                                        #define hOHOhOHoHO sem
                                                                                                                                                                        #define HoHOhOHoHO throw
                                                                                                                                                                        #define hoHOhOHoHO ~Semaphore
                                                                                                                                                                        #define HOhOhOHoHO sem_destroy
                                                                                                                                                                        #define hOhOhOHoHO p
                                                                                                                                                                        #define HohOhOHoHO sem_wait
                                                                                                                                                                        #define hohOhOHoHO v
                                                                                                                                                                        #define HOHohOHoHO sem_post
                                                                                                                                                                        #define hOHohOHoHO sem_t
                                                                                                                                                                        #define HoHohOHoHO friend
                                                                                                                                                                        #define hoHohOHoHO w
                                                                                                                                                                        #define HOhohOHoHO waitingCount
                                                                                                                                                                        #define hOhohOHoHO w.p
                                                                                                                                                                        #define HohohOHoHO bool
                                                                                                                                                                        #define hohohOHoHO signal
                                                                                                                                                                        #define HOHOHoHoHO w.v
                                                                                                                                                                        #define hOHOHoHoHO true
                                                                                                                                                                        #define HoHOHoHoHO false
                                                                                                                                                                        #define hoHOHoHoHO s
                                                                                                                                                                        #define HOhOHoHoHO s.p
                                                                                                                                                                        #define hOhOHoHoHO s.v
                                                                                                                                                                        #define HohOHoHoHO cond
                                                                                                                                                                        #define hohOHoHoHO cond.waitingCount
                                                                                                                                                                        #define HOHoHoHoHO cond.wait
                                                                                                                                                                        #define hOHoHoHoHO cond.signal
                                                                                                                                                                        #define HoHoHoHoHO INT_MIN
                                                                                                                                                                        #define hoHoHoHoHO 0x80000000;
                                                                                                                                                                        #define HOhoHoHoHO FREE
                                                                                                                                                                        #define hOhoHoHoHO -5;
                                                                                                                                                                        #define HohoHoHoHO circularBuffer::put
                                                                                                                                                                        #define hohoHoHoHO elem
                                                                                                                                                                        #define HOHOhoHoHO circularBuffer::get
                                                                                                                                                                        #define hOHOhoHoHO tmp
                                                                                                                                                                        #define HoHOhoHoHO circularBuffer::peak_head
                                                                                                                                                                        #define hoHOhoHoHO circularBuffer::print
                                                                                                                                                                        #define HOhOhoHoHO newsize
                                                                                                                                                                        #define hOhOhoHoHO print
