#include "defines.h"
#include "monitor.h"
#include "queue.hpp"
#include <iostream>

HOHOHOHOHO hOHOHOHOHO HoHOHOHOHO hoHOHOHOHO HOhOHOHOHO
hOhOHOHOHO
HohOHOHOHO
    hOHOHOHOHO hohOHOHOHO HOHoHOHOHO hOHoHOHOHO HoHoHOHOHO HoHOHOHOHO HOhOHOHOHO hohOHOHOHO hOHoHOHOHO HoHoHOHOHO hOhOHOHOHO hoHoHOHOHO
    HOHoHOHOHO HOhoHOHOHO hohOHOHOHO HOHoHOHOHO hOhoHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO hohoHOHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO HOHOhOHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO hOHOhOHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO HoHOhOHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO hoHOhOHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO HohoHOHOHO

HOHoHOHOHO HOhOhOHOHO hohOHOHOHO HOHoHOHOHO hOhoHOHOHO HoHoHOHOHO 
hOhOHOHOHO
    HOHoHOHOHO hOhOhOHOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HOHohOHOHO hohOHOHOHO HOHoHOHOHO hOHohOHOHO HohOhOHOHO HoHohOHOHO HohoHOHOHO hOHohOHOHO hoHohOHOHO HOhohOHOHO HohoHOHOHO hOHohOHOHO HohOhOHOHO hohOHOHOHO hOHohOHOHO hOhohOHOHO HohohOHOHO HoHoHOHOHO hohohOHOHO hOHoHOHOHO HoHoHOHOHO
        HOHOHoHOHO hohOHOHOHO hOHOHoHOHO HoHOHoHOHO hOHohOHOHO hoHOHoHOHO hohohOHOHO HOhOHoHOHO hOhOHoHOHO hOhoHOHOHO HoHoHOHOHO
            hOhOhOHOHO HohOHoHOHO HohoHOHOHO
    hohOHoHOHO hOhOhOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HOHoHoHOHO hohOHOHOHO HoHoHOHOHO 
hOhOHOHOHO
    HOHoHOHOHO hOhOhOHOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HOHohOHOHO hohOHOHOHO HOHoHOHOHO hOHohOHOHO HohOhOHOHO HoHohOHOHO HohoHOHOHO hOHohOHOHO hoHohOHOHO HOhohOHOHO HohoHOHOHO hOHohOHOHO HohOhOHOHO hohOHOHOHO hOHohOHOHO hOhohOHOHO HohohOHOHO HoHoHOHOHO hohohOHOHO hOHoHOHOHO HoHoHOHOHO
        hOhOhOHOHO HohOHoHOHO HohoHOHOHO
    hohOHoHOHO hOhOhOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO hOHoHoHOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    hohOHoHOHO hohOHOHOHO HOhoHOHOHO hohOHOHOHO hohOhOHOHO HoHoHOHOHO HoHoHoHOHO hoHoHoHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HOhoHoHOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    hohOHoHOHO hohOHOHOHO HOhoHOHOHO hohOHOHOHO hohOhOHOHO HoHoHOHOHO hOhoHoHOHO HOhoHOHOHO hohOHOHOHO HohohOHOHO HoHoHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HohoHoHOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    hohOHoHOHO hohOHOHOHO hohoHOHOHO hohOHOHOHO HoHoHOHOHO hOhoHoHOHO hohoHoHOHO HOHOhoHOHO hOHOhoHOHO hohOHOHOHO HoHoHOHOHO hohohOHOHO HOhOHoHOHO hOhOHoHOHO hohOhOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HoHOhoHOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    hohOHoHOHO hohOHOHOHO hohoHOHOHO hohOHOHOHO HoHoHOHOHO hOhoHoHOHO hoHOhoHOHO HOHOhoHOHO hOHOhoHOHO hohOHOHOHO HoHoHOHOHO hohohOHOHO HOhOHoHOHO hOhOHoHOHO HohohOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HOHOHOHOHO HOhOhoHOHO HoHOHOHOHO hoHOHOHOHO hOhOhoHOHO
hOhOHOHOHO
HohOhoHOHO 
    hohOhoHOHO HOHohoHOHO hOhOHOHOHO hOHohoHOHO HohOhOHOHO hohOhOHOHO HoHohoHOHO hoHohoHOHO HohOhOHOHO HohohOHOHO HoHohoHOHO HOhohoHOHO HohOhOHOHO HOhOHoHOHO HoHohoHOHO hOhohoHOHO HohOhOHOHO hohoHoHOHO hoHoHOHOHO HohoHOHOHO
    HohohoHOHO hohohoHOHO HoHOHoHOHO HOHOHOhOHO hoHOHoHOHO HohoHOHOHO
    HOHoHOHOHO hOHOHOhOHO HoHOHoHOHO HOHOHOhOHO hoHOHoHOHO HohoHOHOHO
    hOHOHOHOHO HoHOHOhOHO HohoHOHOHO
HohOHOHOHO
    HOhOhoHOHO hohOHOHOHO HOHoHOHOHO hoHOHOhOHO HoHoHOHOHO
    hOhOHOHOHO
        hOHOHoHOHO HohOhOHOHO HOhOHOhOHO hOHOHOHOHO hohOHOHOHO hoHOHOhOHO HoHoHOHOHO HohoHOHOHO
        hOHOHOhOHO HoHOHoHOHO hohOhOHOHO hoHOHoHOHO HohOhOHOHO hOHOHOhOHO HoHOHoHOHO HohohOHOHO hoHOHoHOHO HohOhOHOHO hOHOHOhOHO HoHOHoHOHO HOhOHoHOHO hoHOHoHOHO HohOhOHOHO hOHOHOhOHO HoHOHoHOHO hohoHoHOHO hoHOHoHOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    hoHoHOHOHO
    hOhOHOhOHO HohOHOhOHO hohOHOHOHO HOHohoHOHO hohOHOhOHO HoHoHOHOHO HohoHOHOHO
    hOhOHOhOHO HOHoHOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hOhOHOhOHO hOHoHOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hOhOHOhOHO HoHoHOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hOhOHOhOHO hoHoHOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOhoHOhOHO hOhOHOhOHO hOhoHOhOHO hohOHOHOHO hOhOHOhOHO HohoHOhOHO HoHoHOHOHO
    hOhOHOHOHO
        hohOHoHOHO hohOHOHOHO hohOHOHOHO hohoHOhOHO HoHoHOHOHO HOHOhOhOHO HoHoHOHOHO hOHOhOhOHO HoHOhOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
    HOhoHOhOHO hOhOHOhOHO hoHOhOhOHO hohOHOHOHO hOhOHOhOHO HohoHOhOHO HoHoHOHOHO
    hOhOHOHOHO
        hohOHoHOHO hohOHOHOHO hohOHOHOHO hohoHOhOHO HoHoHOHOHO HOHOhOhOHO HoHoHOHOHO hOHOhOhOHO HOhOhOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
    HOhoHOhOHO hOhOHOhOHO hOhOhOhOHO hohOHOHOHO hOhOHOhOHO HohoHOhOHO HoHoHOHOHO
    hOhOHOHOHO
        hohOHoHOHO hohOHOHOHO hohOHOHOHO hohoHOhOHO HoHoHOHOHO HOHOhOhOHO HoHoHOHOHO hOHOhOhOHO HohOhOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
    HOhoHOhOHO hOhOHOhOHO hohOhOhOHO hohOHOHOHO hOhOHOhOHO HohoHOhOHO HoHoHOHOHO
    hOhOHOHOHO
        hohOHoHOHO hohOHOHOHO hohOHOHOHO hohoHOhOHO HoHoHOHOHO HOHOhOhOHO HoHoHOHOHO hOHOhOhOHO HOHohOhOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
hoHoHOHOHO HohoHOHOHO

hOhOHOhOHO hOHohOhOHO hohOHOHOHO HOHohoHOHO hohOHOhOHO HoHoHOHOHO
hOhOHOHOHO
    HoHohOhOHO hoHohOhOHO hohOHOHOHO hohOHOhOHO hOhOHoHOHO HOhohOhOHO HoHoHOHOHO HOHOhoHOHO hOHOHoHOHO hOHOhOhOHO HOHOhOHOHO hohOHOHOHO HoHoHOHOHO 
    HOHOhoHOHO hOHOHOhOHO HoHOHoHOHO HOhohOhOHO hoHOHoHOHO hOhoHoHOHO hohOhOHOHO HoHoHOHOHO
        hOhohOhOHO hohohoHOHO HoHOHoHOHO HOhohOhOHO hoHOHoHOHO HohohOhOHO

    hohohOhOHO HoHohOhOHO hoHohOhOHO hohOHOHOHO hohOHOhOHO hOhOHoHOHO HOHOHohOHO HoHoHOHOHO HOHOhoHOHO hOHOHoHOHO hOHOhOhOHO hOHOhOHOHO hohOHOHOHO HoHoHOHOHO 
    HOHOhoHOHO hOHOHOhOHO HoHOHoHOHO HOHOHohOHO hoHOHoHOHO hOhoHoHOHO hohOhOHOHO HoHoHOHOHO
        hOhohOhOHO hohohoHOHO HoHOHoHOHO HOHOHohOHO hoHOHoHOHO HohohOhOHO

    hohohOhOHO HoHohOhOHO hoHohOhOHO hohOHOHOHO hohOHOhOHO hOhOHoHOHO hOHOHohOHO HoHoHOHOHO HOHOhoHOHO hOHOHoHOHO hOHOhOhOHO HoHOhOHOHO hohOHOHOHO HoHoHOHOHO 
    HOHOhoHOHO hOHOHOhOHO HoHOHoHOHO hOHOHohOHO hoHOHoHOHO hOhoHoHOHO hohOhOHOHO HoHoHOHOHO
        hOhohOhOHO hohohoHOHO HoHOHoHOHO hOHOHohOHO hoHOHoHOHO HohohOhOHO

    hohohOhOHO HoHohOhOHO hoHohOhOHO hohOHOHOHO hohOHOhOHO hOhOHoHOHO HoHOHohOHO HoHoHOHOHO HOHOhoHOHO hOHOHoHOHO hOHOhOhOHO hoHOhOHOHO hohOHOHOHO HoHoHOHOHO 
    HOHOhoHOHO hOHOHOhOHO HoHOHoHOHO HoHOHohOHO hoHOHoHOHO hOhoHoHOHO hohOhOHOHO HoHoHOHOHO
        hOhohOhOHO hohohoHOHO HoHOHoHOHO HoHOHohOHO hoHOHoHOHO HohohOhOHO

    hohohOhOHO hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO HOhOHohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    HOHoHOHOHO hOhOHohOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HohOHohOHO hohOHOHOHO hohOHohOHO hohOHOHOHO HOHoHohOHO HoHoHOHOHO hOhohOHOHO hOHoHohOHO HohohOhOHO
    HoHoHohOHO hohOHOHOHO HohohOHOHO HoHoHOHOHO
    hOhOHOHOHO
        hoHoHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        HOHOHoHOHO hohOHOHOHO hoHohOhOHO hOHOHoHOHO hOHOhOhOHO HOHOhOHOHO hohOHOHOHO HoHoHOHOHO HoHoHOHOHO hOhOHOHOHO
            HohOHoHOHO hOHOHOhOHO HoHOHoHOHO HOhohOhOHO hoHOHoHOHO HohoHOHOHO
            HOhoHohOHO hohOHOHOHO hohohoHOHO HoHOHoHOHO HOhohOhOHO hoHOHoHOHO HoHoHOHOHO HohoHOHOHO
            hOhoHohOHO hOHOHOhOHO HoHOHoHOHO HOhohOhOHO hoHOHoHOHO HohoHOHOHO
        hoHoHOHOHO
        hOHOHoHOHO hOHOhOhOHO HohoHohOHO hohOHOHOHO hOhOHohOHO HoHoHOHOHO HohoHOHOHO
        hohoHohOHO HOHOhohOHO "(A1) - Produced: " HOHOhohOHO hOhOHohOHO HOHOhohOHO hOHOhohOHO HohoHOHOHO
        hOhOHohOHO HohOhOHOHO hohOHOHOHO hOhOHohOHO hOhohOHOHO HOhOHoHOHO HoHoHOHOHO hohohOHOHO HoHOhohOHO HohoHOHOHO
        HohOHOhOHO hohOHOHOHO HOhohOhOHO HoHoHOHOHO HohoHOHOHO 
        hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hoHOhohOHO hohOHOHOHO HOhOhohOHO hOhOhohOHO hohOHOHOHO HohOhohOHO hohohOHOHO hoHoHoHOHO HoHoHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
hoHoHOHOHO

hOhOHOhOHO hohOhohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    HOHoHOHOHO hOhOHohOHO HohOhOHOHO HohohOHOHO HohoHOHOHO

    HohOHohOHO hohOHOHOHO hohOHohOHO hohOHOHOHO HOHoHohOHO HoHoHOHOHO hOhohOHOHO HOHohohOHO HohohOhOHO
    HoHoHohOHO hohOHOHOHO HohohOHOHO HoHoHOHOHO 
    hOhOHOHOHO
        hoHoHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        HOHOHoHOHO hohOHOHOHO hoHohOhOHO hOHOHoHOHO hOHOhOhOHO hOHOhOHOHO hohOHOHOHO HoHoHOHOHO HoHoHOHOHO hOhOHOHOHO
            HohOHoHOHO hOHOHOhOHO HoHOHoHOHO HOHOHohOHO hoHOHoHOHO HohoHOHOHO
            HOhoHohOHO hohOHOHOHO hohohoHOHO HoHOHoHOHO HOHOHohOHO hoHOHoHOHO HoHoHOHOHO HohoHOHOHO
            hOhoHohOHO hOHOHOhOHO HoHOHoHOHO HOHOHohOHO hoHOHoHOHO HohoHOHOHO
        hoHoHOHOHO
        hOHOHoHOHO hOHOhOhOHO HohoHohOHO hohOHOHOHO hOhOHohOHO HoHoHOHOHO HohoHOHOHO
        hohoHohOHO HOHOhohOHO "(A2) - Produced: " HOHOhohOHO hOhOHohOHO HOHOhohOHO hOHOhohOHO HohoHOHOHO
        hOhOHohOHO HohOhOHOHO hohOHOHOHO hOhOHohOHO hOhohOHOHO HOhOHoHOHO HoHoHOHOHO hohohOHOHO HoHOhohOHO HohoHOHOHO
        HohOHOhOHO hohOHOHOHO HOHOHohOHO HoHoHOHOHO HohoHOHOHO 
        hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hoHOhohOHO hohOHOHOHO HOhOhohOHO hOhOhohOHO hohOHOHOHO HohOhohOHO hohohOHOHO hoHoHoHOHO HoHoHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
hoHoHOHOHO

hOhOHOhOHO hOHohohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    HOHoHOHOHO HoHohohOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HohOHohOHO hohOHOHOHO hohOHohOHO hohOHOHOHO HOHoHohOHO HoHoHOHOHO hOhohOHOHO HoHOhohOHO HohohOhOHO
    HoHoHohOHO hohOHOHOHO HohohOHOHO HoHoHOHOHO
    hOhOHOHOHO
        hoHoHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        HOHOHoHOHO hohOHOHOHO hoHohOhOHO hOHOHoHOHO hOHOhOhOHO HoHOhOHOHO hohOHOHOHO HoHoHOHOHO HoHoHOHOHO hOhOHOHOHO
            HohOHoHOHO hOHOHOhOHO HoHOHoHOHO hOHOHohOHO hoHOHoHOHO HohoHOHOHO
            HOhoHohOHO hohOHOHOHO hohohoHOHO HoHOHoHOHO hOHOHohOHO hoHOHoHOHO HoHoHOHOHO HohoHOHOHO
            hOhoHohOHO hOHOHOhOHO HoHOHoHOHO hOHOHohOHO hoHOHoHOHO HohoHOHOHO
        hoHoHOHOHO
        HoHohohOHO HohOhOHOHO hOHOHoHOHO hOHOhOhOHO hoHohohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hohoHohOHO HOHOhohOHO "(B1) - Eaten: " HOHOhohOHO HoHohohOHO HOHOhohOHO hOHOhohOHO HohoHOHOHO
        HohOHOhOHO hohOHOHOHO hOHOHohOHO HoHoHOHOHO HohoHOHOHO 
        hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hoHOhohOHO hohOHOHOHO HOhOhohOHO hOhOhohOHO hohOHOHOHO HohOhohOHO hohohOHOHO hoHoHoHOHO HoHoHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
hoHoHOHOHO

hOhOHOhOHO HOhohohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
    HOHoHOHOHO HoHohohOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HohOHohOHO hohOHOHOHO hohOHohOHO hohOHOHOHO HOHoHohOHO HoHoHOHOHO hOhohOHOHO hOhohohOHO HohohOhOHO
    HoHoHohOHO hohOHOHOHO HohohOHOHO HoHoHOHOHO
    hOhOHOHOHO
        hoHoHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        HOHOHoHOHO hohOHOHOHO hoHohOhOHO hOHOHoHOHO hOHOhOhOHO hoHOhOHOHO hohOHOHOHO HoHoHOHOHO HoHoHOHOHO hOhOHOHOHO
            HohOHoHOHO hOHOHOhOHO HoHOHoHOHO HoHOHohOHO hoHOHoHOHO HohoHOHOHO
            HOhoHohOHO hohOHOHOHO hohohoHOHO HoHOHoHOHO HoHOHohOHO hoHOHoHOHO HoHoHOHOHO HohoHOHOHO
            hOhoHohOHO hOHOHOhOHO HoHOHoHOHO HoHOHohOHO hoHOHoHOHO HohoHOHOHO
        hoHoHOHOHO
        HoHohohOHO HohOhOHOHO hOHOHoHOHO hOHOhOhOHO hoHohohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hohoHohOHO HOHOhohOHO "(B2) - Eaten: " HOHOhohOHO HoHohohOHO HOHOhohOHO hOHOhohOHO HohoHOHOHO
        HohOHOhOHO hohOHOHOHO HoHOHohOHO HoHoHOHOHO HohoHOHOHO 
        hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
        hoHOhohOHO hohOHOHOHO HOhOhohOHO hOhOhohOHO hohOHOHOHO HohOhohOHO hohohOHOHO hoHoHoHOHO HoHoHOHOHO HoHoHOHOHO HohoHOHOHO
    hoHoHOHOHO
hoHoHOHOHO


HOHoHOHOHO HohohohOHO hohOHOHOHO HoHoHOHOHO hOhOHOHOHO
    HOhOhoHOHO hohohohOHO HohOhOHOHO HOhOHOhOHO HOhOhoHOHO hohOHOHOHO HOHOHOHoHO HoHoHOHOHO HohoHOHOHO

    hOHOHOHoHO hOHohoHOHO HoHohoHOHO hoHohoHOHO HoHohoHOHO HOhohoHOHO HoHohoHOHO hOhohoHOHO HohoHOHOHO
    HoHOHOHoHO hoHOHOHoHO HoHohoHOHO HOHoHohOHO HoHohoHOHO HOhOHOHoHO HoHohoHOHO hOhOHOHoHO HoHoHOHOHO HohoHOHOHO
    HoHOHOHoHO HohOHOHoHO HoHohoHOHO HOHoHohOHO HoHohoHOHO hohOHOHoHO HoHohoHOHO hOhOHOHoHO HoHoHOHOHO HohoHOHOHO
    HoHOHOHoHO HOHoHOHoHO HoHohoHOHO HOHoHohOHO HoHohoHOHO hOHoHOHoHO HoHohoHOHO hOhOHOHoHO HoHoHOHOHO HohoHOHOHO
    HoHOHOHoHO HoHoHOHoHO HoHohoHOHO HOHoHohOHO HoHohoHOHO hoHoHOHoHO HoHohoHOHO hOhOHOHoHO HoHoHOHOHO HohoHOHOHO  
    
    HOhoHOHoHO hOHohoHOHO HoHohoHOHO HOHoHohOHO HoHoHOHOHO HohoHOHOHO
    HOhoHOHoHO hoHohoHOHO HoHohoHOHO HOHoHohOHO HoHoHOHOHO HohoHOHOHO
    HOhoHOHoHO HOhohoHOHO HoHohoHOHO HOHoHohOHO HoHoHOHOHO HohoHOHOHO
    HOhoHOHoHO hOhohoHOHO HoHohoHOHO HOHoHohOHO HoHoHOHOHO HohoHOHOHO

    hohOHoHOHO hohOhOHOHO HohoHOHOHO
hoHoHOHOHO
