#include "defines.h"
#ifndef __monitor_h
#define __monitor_h

#include <stdio.h> 
#include <stdlib.h> 
#include <sys/types.h> 
#include <sys/stat.h> 
#include <string.h> 
#include <errno.h> 
#include <fcntl.h> 
#include <pthread.h> 
#include <unistd.h>
#include <semaphore.h>



HOHOHOHOHO hOhoHOHoHO
hOhOHOHOHO
HohOHOHOHO

  hOhoHOHoHO hohOHOHOHO HOHoHOHOHO HohoHOHoHO HoHoHOHOHO
  hOhOHOHOHO
     HOHOHoHOHO hohOHOHOHO hohoHOHoHO hohOHOHOHO HOHOhOHoHO hOHOhOHoHO HoHohoHOHO hohOhOHOHO HoHohoHOHO HohoHOHoHO HoHoHOHOHO hoHohOHOHO hohOhOHOHO HoHoHOHOHO
       HoHOhOHoHO "sem_init: failed" HohoHOHOHO
  hoHoHOHOHO
  hoHOhOHoHO hohOHOHOHO HoHoHOHOHO
  hOhOHOHOHO 
  HOhOhOHoHO hohOHOHOHO HOHOhOHoHO hOHOhOHoHO HoHoHOHOHO HohoHOHOHO 
  hoHoHOHOHO

  hOhOHOhOHO hOhOhOHoHO hohOHOHOHO HoHoHOHOHO
  hOhOHOHOHO
     HOHOHoHOHO hohOHOHOHO HohOhOHoHO hohOHOHOHO HOHOhOHoHO hOHOhOHoHO HoHoHOHOHO hoHohOHOHO hohOhOHOHO HoHoHOHOHO
       HoHOhOHoHO "sem_wait: failed" HohoHOHOHO
  hoHoHOHOHO

  hOhOHOhOHO hohOhOHoHO hohOHOHOHO HoHoHOHOHO
  hOhOHOHOHO
     HOHOHoHOHO hohOHOHOHO HOHohOHoHO hohOHOHOHO HOHOhOHoHO hOHOhOHoHO HoHoHOHOHO hoHohOHOHO hohOhOHOHO HoHoHOHOHO
       HoHOhOHoHO "sem_post: failed" HohoHOHOHO
  hoHoHOHOHO
  

HohOhoHOHO

hOHohOHoHO hOHOhOHoHO HohoHOHOHO
hoHoHOHOHO HohoHOHOHO

HOHOHOHOHO HohohoHOHO
hOhOHOHOHO
  HoHohOHoHO HOHOHOHOHO hOhOhoHOHO HohoHOHOHO

HohOHOHOHO
HohohoHOHO hohOHOHOHO HoHoHOHOHO HoHOHOHOHO hoHohOHoHO hohOHOHOHO hohOhOHOHO HoHoHOHOHO
hOhOHOHOHO
HOhohOHoHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO HOhoHohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
hOhohOHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HohohOHoHO hohohOHoHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
HOHOHoHOHO hohOHOHOHO HOhohOHoHO HoHoHOHOHO
hOhOHOHOHO
hOhoHohOHO HOhohOHoHO HohoHOHOHO
HOHOHoHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hohOHoHOHO hOHOHoHoHO HohoHOHOHO
hoHoHOHOHO
hohohOhOHO
hohOHoHOHO HoHOHoHoHO HohoHOHOHO
hoHoHOHOHO

HohOhoHOHO
hOhoHOHoHO hoHohOHoHO HohoHOHOHO
HOHoHOHOHO HOhohOHoHO HohoHOHOHO
hoHoHOHOHO HohoHOHOHO


HOHOHOHOHO hOhOhoHOHO
hOhOHOHOHO
HohOHOHOHO
hOhOhoHOHO hohOHOHOHO HoHoHOHOHO HoHOHOHOHO hoHOHoHoHO hohOHOHOHO HohohOHOHO HoHoHOHOHO hOhOHOHOHO hoHoHOHOHO

hOhOHOhOHO hoHoHohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
HOhOHoHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO hoHOHohOHO hohOHOHOHO HoHoHOHOHO
hOhOHOHOHO
hOhOHoHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO HOhoHohOHO hohOHOHOHO HohohoHOHO HOHOhOHoHO HohOHoHoHO HoHoHOHOHO
hOhOHOHOHO
HohOHoHOHO hohOHoHoHO HohoHOHOHO
hoHOHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
HOHoHoHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO hohohOHoHO hohOHOHOHO HohohoHOHO HOHOhOHoHO HohOHoHoHO HoHoHOHOHO
hOhOHOHOHO
HOHOHoHOHO hohOHOHOHO hOHoHoHoHO hohOHOHOHO HoHoHOHOHO HoHoHOHOHO
hoHoHohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO


HohOhoHOHO
hOhoHOHoHO hoHOHoHoHO HohoHOHOHO
hoHoHOHOHO HohoHOHOHO

#endif
