#include "defines.h"
#include "queue.hpp"

HOhoHOhOHO HOHoHOHOHO HoHoHoHoHO HohOhOHOHO hoHoHoHoHO
HOhoHOhOHO HOHoHOHOHO HOhoHoHoHO HohOhOHOHO hOhoHoHoHO

hOhOHOhOHO HohoHoHoHO hohOHOHOHO HOHoHOHOHO hohoHoHoHO HoHoHOHOHO hOhOHOHOHO
    hOHOHoHOHO HoHOHoHOHO HOhohOHOHO hoHOHoHOHO HohOhOHOHO hohoHoHoHO HohoHOHOHO
    HOhohOHOHO HohOhOHOHO hohOHOHOHO HOhohOHOHO hOhohOHOHO HohohOHOHO HoHoHOHOHO hohohOHOHO hOHoHOHOHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HOHOhoHoHO hohOHOHOHO HoHoHOHOHO hOhOHOHOHO
    HOHoHOHOHO hOHOhoHoHO HohOhOHOHO hOHOHoHOHO HoHOHoHOHO HoHohOHOHO hoHOHoHOHO HohoHOHOHO
       
    HOHOHoHOHO hohOHOHOHO HoHohOHOHO hOhOHoHOHO HOhohOHOHO HoHoHOHOHO hohOHoHOHO HoHoHoHoHO HohoHOHOHO
    hOHOHoHOHO HoHOHoHOHO HoHohOHOHO hoHOHoHOHO HohOhOHOHO HOhoHoHoHO HohoHOHOHO
    HoHohOHOHO HohOhOHOHO hohOHOHOHO HoHohOHOHO hOhohOHOHO HohohOHOHO HoHoHOHOHO hohohOHOHO hOHoHOHOHO HohoHOHOHO
    hohOHoHOHO hOHOhoHoHO HohoHOHOHO
hoHoHOHOHO

HOHoHOHOHO HoHOhoHoHO hohOHOHOHO HoHoHOHOHO hOhOHOHOHO
    HOHOHoHOHO hohOHOHOHO HoHohOHOHO hOhOHoHOHO HOhohOHOHO HoHoHOHOHO hohOHoHOHO HoHoHoHoHO HohoHOHOHO

    hohOHoHOHO hOHOHoHOHO HoHOHoHOHO HoHohOHOHO hoHOHoHOHO HohoHOHOHO
hoHoHOHOHO

hOhOHOhOHO hoHOhoHoHO hohOHOHOHO HoHoHOHOHO hOhOHOHOHO
    hohoHohOHO HOHOhohOHO "Actual Buffer HoHOHOHOHO HoHOHoHOHO " HohoHOHOHO
    HOHohOHOHO hohOHOHOHO HOHoHOHOHO hOHohOHOHO HohOhOHOHO HoHohOHOHO HohoHOHOHO hOHohOHOHO hoHohOHOHO HOhohOHOHO HohoHOHOHO hOHohOHOHO HohOhOHOHO hohOHOHOHO hOHohOHOHO hOhohOHOHO HohohOHOHO HoHoHOHOHO hohohOHOHO hOHoHOHOHO HoHoHOHOHO
        hohoHohOHO HOHOhohOHO hOHOHoHOHO HoHOHoHOHO hOHohOHOHO hoHOHoHOHO HOHOhohOHO ", " HohoHOHOHO
    hohoHohOHO HOHOhohOHO "\n" HohoHOHOHO
hoHoHOHOHO

       
