#include "defines.h"
#ifndef __queue_hpp
#define __queue_hpp

#include <iostream>

HOHOHOHOHO HOhOHOHOHO 
hOhOHOHOHO
HohOHOHOHO 
    HOHoHOHOHO HoHohOHOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HOHoHOHOHO HOhohOHOHO HohOhOHOHO hohOhOHOHO HohoHOHOHO
    HOHoHOHOHO hOHoHOHOHO HohoHOHOHO
    HOHoHOHOHO HoHOHOhOHO HohoHOHOHO

    HOhOHOHOHO hohOHOHOHO HOHoHOHOHO HOhOhoHoHO HoHoHOHOHO 
    hOhOHOHOHO  
        hOHoHOHOHO HohOhOHOHO HOhOhoHoHO HohoHOHOHO
        hOHOHoHOHO HohOhOHOHO HOhOHOhOHO HOHoHOHOHO HoHOHoHOHO HOhOhoHoHO hoHOHoHOHO HohoHOHOHO
    hoHoHOHOHO
    hOhOHOhOHO HohoHohOHO hohOHOHOHO HOHoHOHOHO hohoHoHoHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO hoHohohOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    HOHoHOHOHO hOHOhoHOHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
    hOhOHOhOHO hOhOhoHoHO hohOHOHOHO HoHoHOHOHO HohoHOHOHO
hoHoHOHOHO HohoHOHOHO

#endif
